# Generated by Django 5.2.12 on 2026-03-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalprofile_historicalrole_historicaluser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Microcredit Hub', max_length=150, verbose_name='Nome do sistema')),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Logo (URL)')),
                ('primary_color', models.CharField(default='#0f766e', help_text='Hex ou nome de cor CSS para destacar botões e cabeçalhos.', max_length=20, verbose_name='Cor primária')),
                ('tagline', models.CharField(blank=True, help_text='Pequena frase que aparece no topo/login.', max_length=200, verbose_name='Frase de impacto')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
    ]
