# Generated by Django 5.2.12 on 2026-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Quando activo, apenas superusers conseguem aceder ao sistema.', verbose_name='Sistema bloqueado'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='locked_message',
            field=models.TextField(blank=True, help_text='Texto mostrado aos utilizadores quando o sistema está temporariamente indisponível.', verbose_name='Mensagem de bloqueio'),
        ),
    ]
