# Generated by Django 5.2.12 on 2026-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_systemsettings_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='login_card_color',
            field=models.CharField(blank=True, help_text='Cor de fundo específica para o cartão de login (deixe vazio para usar o padrão).', max_length=20, verbose_name='Cor do cartão de login'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='name',
            field=models.CharField(default='MAKIRA', max_length=150, verbose_name='Nome do sistema'),
        ),
    ]
