# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_systemsettings_login_card_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='login_description',
            field=models.TextField(
                blank=True,
                help_text='Parágrafo exibido no painel esquerdo do login (ecrã grande).',
                verbose_name='Descrição do painel esquerdo',
            ),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='login_banner_color',
            field=models.CharField(
                blank=True,
                help_text='Cor do painel esquerdo. Vazio = usa cor primária.',
                max_length=20,
                verbose_name='Cor do banner esquerdo (login)',
            ),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='tagline',
            field=models.CharField(
                blank=True,
                help_text='Ex.: Gestão moderna de microcrédito.',
                max_length=200,
                verbose_name='Frase de impacto (painel esquerdo)',
            ),
        ),
    ]
