# Generated by Django 5.2.12 on 2026-03-10 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0004_add_receipt_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('event_type', models.CharField(choices=[('meeting', 'Reunião'), ('alert', 'Alerta'), ('reminder', 'Lembrete'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('notify', models.BooleanField(default=True, verbose_name='Enviar notificação')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='Cliente')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montante (MT)')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='loans.loan', verbose_name='Empréstimo (opcional)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Evento de calendário',
                'verbose_name_plural': 'Eventos de calendário',
                'ordering': ['date', 'title'],
                'indexes': [models.Index(fields=['user', 'date'], name='calendario__user_id_bf8067_idx'), models.Index(fields=['date'], name='calendario__date_0c1c72_idx')],
            },
        ),
    ]
