# Generated by Django 5.2.12 on 2026-03-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_add_event_type_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cor (hex)'),
        ),
    ]
