# Generated by Django 5.2.12 on 2026-03-10 10:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montante')),
                ('date', models.DateField(verbose_name='Data')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan', verbose_name='Empréstimo')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'historical Transação',
                'verbose_name_plural': 'historical Transações',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída')], max_length=20, verbose_name='Tipo')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montante')),
                ('date', models.DateField(verbose_name='Data')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loans.loan', verbose_name='Empréstimo')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['type'], name='accounting__type_3c86cb_idx'), models.Index(fields=['date'], name='accounting__date_98b3df_idx'), models.Index(fields=['category'], name='accounting__categor_7adcd7_idx')],
            },
        ),
    ]
