# Generated by Django 5.2.12 on 2026-03-12 07:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor do imposto'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Taxa do imposto (snapshot)'),
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total (base + imposto)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor do imposto'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Taxa do imposto (snapshot)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total (base + imposto)'),
        ),
        migrations.CreateModel(
            name='HistoricalTax',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='Código')),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Percentagem (0-1)')),
                ('scope', models.CharField(choices=[('ambos', 'Entradas e Saídas'), ('entrada', 'Apenas Entradas'), ('saida', 'Apenas Saídas')], default='ambos', max_length=20, verbose_name='Aplicação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Imposto',
                'verbose_name_plural': 'historical Impostos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Percentagem (0-1)')),
                ('scope', models.CharField(choices=[('ambos', 'Entradas e Saídas'), ('entrada', 'Apenas Entradas'), ('saida', 'Apenas Saídas')], default='ambos', max_length=20, verbose_name='Aplicação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Imposto',
                'verbose_name_plural': 'Impostos',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='accounting__is_acti_121ee0_idx'), models.Index(fields=['code'], name='accounting__code_2ff627_idx')],
            },
        ),
        migrations.AddField(
            model_name='historicaltransaction',
            name='tax',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounting.tax', verbose_name='Imposto'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounting.tax', verbose_name='Imposto'),
        ),
    ]
