# Generated by Django 5.2.12 on 2026-03-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_monthlyfinancesnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlyfinancesnapshot',
            new_name='accounting__month_c72bb0_idx',
            old_name='accounting_m_month_3e3de7_idx',
        ),
    ]
