# Generated by Django 5.2.12 on 2026-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_merge_0005_accounting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlysnapshotactionlog',
            new_name='accounting__snapsho_5c3902_idx',
            old_name='accounting_m_snapsho_84b66e_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlysnapshotactionlog',
            new_name='accounting__action_4c1289_idx',
            old_name='accounting_m_action_8c6e6b_idx',
        ),
    ]
