# Generated by Django 5.2.12 on 2026-03-10 10:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário base')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20, verbose_name='Estado')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor (calendário)')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Entrada')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Saída')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atrasado', 'Atrasado'), ('ferias', 'Férias'), ('justificado', 'Justificado')], default='presente', max_length=20, verbose_name='Estado')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas trabalhadas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Registo de ponto',
                'verbose_name_plural': 'Registos de ponto',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Entrada')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Saída')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atrasado', 'Atrasado'), ('ferias', 'Férias'), ('justificado', 'Justificado')], default='presente', max_length=20, verbose_name='Estado')),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Horas trabalhadas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='Colaborador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Registo de ponto',
                'verbose_name_plural': 'historical Registos de ponto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário base')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20, verbose_name='Estado')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de admissão')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor (calendário)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'historical Colaborador',
                'verbose_name_plural': 'historical Colaboradores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSalarySlip',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Mês (YYYY-MM)')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário base')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Horas extras')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bónus')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário bruto')),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='INSS')),
                ('irps', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IRPS')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Outras deduções')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total deduções')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário líquido')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='Colaborador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Recibo de vencimento',
                'verbose_name_plural': 'historical Recibos de vencimento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVacation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data início')),
                ('end_date', models.DateField(verbose_name='Data fim')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='Colaborador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Férias',
                'verbose_name_plural': 'historical Férias',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Mês (YYYY-MM)')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário base')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Horas extras')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bónus')),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário bruto')),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='INSS')),
                ('irps', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IRPS')),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Outras deduções')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total deduções')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salário líquido')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='hr.employee', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Recibo de vencimento',
                'verbose_name_plural': 'Recibos de vencimento',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Data início')),
                ('end_date', models.DateField(verbose_name='Data fim')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='hr.employee', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Férias',
                'verbose_name_plural': 'Férias',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['status'], name='hr_employee_status_75bd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='hr_employee_departm_343e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['employee', 'date'], name='hr_attendan_employe_0dcc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryslip',
            index=models.Index(fields=['employee', 'month'], name='hr_salarysl_employe_089bc7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together={('employee', 'month')},
        ),
        migrations.AddIndex(
            model_name='vacation',
            index=models.Index(fields=['employee'], name='hr_vacation_employe_364beb_idx'),
        ),
        migrations.AddIndex(
            model_name='vacation',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_vacation_start_d_bcf688_idx'),
        ),
    ]
