# Generated by Django 5.2.12 on 2026-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='inss_rate',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=6, verbose_name='Taxa INSS (0-1)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='irps_rate',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=6, verbose_name='Taxa IRPS (0-1)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_deductions_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=6, verbose_name='Outras deduções (0-1)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='overtime_rate_default',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=6, verbose_name='Horas extra padrão (0-1 do salário base)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='penalty_absent_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Penalização por falta (0-1 por ocorrência)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='penalty_late_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Penalização por atraso (0-1 por ocorrência)'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='inss_rate',
            field=models.DecimalField(decimal_places=4, default=0.03, max_digits=6, verbose_name='Taxa INSS (0-1)'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='irps_rate',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=6, verbose_name='Taxa IRPS (0-1)'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='other_deductions_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=6, verbose_name='Outras deduções (0-1)'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='overtime_rate_default',
            field=models.DecimalField(decimal_places=4, default=0.05, max_digits=6, verbose_name='Horas extra padrão (0-1 do salário base)'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='penalty_absent_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Penalização por falta (0-1 por ocorrência)'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='penalty_late_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Penalização por atraso (0-1 por ocorrência)'),
        ),
    ]
