# Generated by Django 5.2.12 on 2026-03-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_inss_rate_employee_irps_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekend_days', models.JSONField(default=list, verbose_name='Dias de fim‑de‑semana')),
                ('workday_start', models.TimeField(default='08:00', verbose_name='Entrada (dias úteis)')),
                ('workday_end', models.TimeField(default='17:00', verbose_name='Saída (dias úteis)')),
                ('weekend_start', models.TimeField(default='08:00', verbose_name='Entrada (fim‑de‑semana)')),
                ('weekend_end', models.TimeField(default='13:00', verbose_name='Saída (fim‑de‑semana)')),
                ('auto_fill_attendance', models.BooleanField(default=True, verbose_name='Auto-preencher presenças em falta (ausente)')),
            ],
            options={
                'verbose_name': 'Configuração de RH',
                'verbose_name_plural': 'Configurações de RH',
            },
        ),
    ]
