# Generated by Django 5.2.12 on 2026-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_hrsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='overtime_rate_default',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Horas extra padrão (0-1 do salário base)'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='overtime_rate_default',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6, verbose_name='Horas extra padrão (0-1 do salário base)'),
        ),
    ]
