# Generated by Django 5.2.12 on 2026-03-11 08:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_overtime_rate_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPayrollAdjustment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Mês (YYYY-MM)')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Horas extra (valor)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bónus (valor)')),
                ('other_deductions_manual', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Outros descontos (manual)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hr.employee', verbose_name='Colaborador')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lançamento de folha',
                'verbose_name_plural': 'historical Lançamentos de folha',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, verbose_name='Mês (YYYY-MM)')),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Horas extra (valor)')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bónus (valor)')),
                ('other_deductions_manual', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Outros descontos (manual)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='hr.employee', verbose_name='Colaborador')),
            ],
            options={
                'verbose_name': 'Lançamento de folha',
                'verbose_name_plural': 'Lançamentos de folha',
                'ordering': ['-month', 'employee_id'],
                'indexes': [models.Index(fields=['month'], name='hr_payrolla_month_d5f212_idx'), models.Index(fields=['employee', 'month'], name='hr_payrolla_employe_329744_idx')],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
