# Generated by Django 5.2.12 on 2026-03-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_historicalpayrolladjustment_payrolladjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrsettings',
            name='auto_detect_late',
            field=models.BooleanField(default=True, help_text="Marca como 'atrasado' quando check_in ultrapassa a entrada + tolerância.", verbose_name='Detectar atraso automaticamente'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='good_hours_ratio',
            field=models.DecimalField(decimal_places=4, default=0.9, max_digits=6, verbose_name='Semáforo horas: Verde (ratio)'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='late_grace_minutes',
            field=models.PositiveIntegerField(default=10, help_text='Minutos de tolerância após a hora de entrada.', verbose_name='Tolerância de atraso (min)'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='ok_hours_ratio',
            field=models.DecimalField(decimal_places=4, default=0.75, max_digits=6, verbose_name='Semáforo horas: Amarelo (ratio)'),
        ),
    ]
