# Generated by Django 5.2.12 on 2026-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_payrolladjustment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayrolladjustment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do lançamento'),
        ),
    ]
