# Generated by Django 5.2.12 on 2026-03-10 10:55

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoan',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montante')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taxa de juro (%)')),
                ('term', models.PositiveIntegerField(verbose_name='Prazo (meses)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Data início')),
                ('end_date', models.DateField(verbose_name='Data fim')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prestação mensal')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montante total')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empréstimo',
                'verbose_name_plural': 'historical Empréstimos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montante')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taxa de juro (%)')),
                ('term', models.PositiveIntegerField(verbose_name='Prazo (meses)')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(verbose_name='Data início')),
                ('end_date', models.DateField(verbose_name='Data fim')),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prestação mensal')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montante total')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montante')),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado')], default='pendente', max_length=20, verbose_name='Estado')),
                ('method', models.CharField(choices=[('transferencia', 'Transferência'), ('m_pesa', 'M-Pesa'), ('deposito', 'Depósito'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Método')),
                ('installment_number', models.PositiveIntegerField(default=1, verbose_name='Número da prestação')),
                ('receipt', models.CharField(blank=True, max_length=200, verbose_name='Recibo')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'historical Pagamento',
                'verbose_name_plural': 'historical Pagamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montante')),
                ('date', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado')], default='pendente', max_length=20, verbose_name='Estado')),
                ('method', models.CharField(choices=[('transferencia', 'Transferência'), ('m_pesa', 'M-Pesa'), ('deposito', 'Depósito'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Método')),
                ('installment_number', models.PositiveIntegerField(default=1, verbose_name='Número da prestação')),
                ('receipt', models.CharField(blank=True, max_length=200, verbose_name='Recibo')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['client'], name='loans_loan_client__f826ee_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['start_date'], name='loans_loan_start_d_e22f07_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['loan'], name='loans_payme_loan_id_35d8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='loans_payme_status_94aae6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='loans_payme_date_567bc9_idx'),
        ),
    ]
