# Generated by Django 5.2.12 on 2026-03-10 13:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCollateral',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição detalhada do item de garantia', max_length=500, verbose_name='Descrição do item')),
                ('item_type', models.CharField(choices=[('documento', 'Documento'), ('eletronico', 'Eletrónico'), ('veiculo', 'Veículo'), ('imovel', 'Imóvel'), ('joias', 'Joias/Ourivesaria'), ('maquinaria', 'Maquinaria/Equipamento'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo de item')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor estimado (MT)')),
                ('condition', models.CharField(choices=[('novo', 'Novo'), ('bom', 'Bom estado'), ('usado', 'Usado'), ('danificado', 'Danificado'), ('não_aplicavel', 'Não aplicável')], default='não_aplicavel', max_length=30, verbose_name='Estado/Conservação')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de série / Identificação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loan', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'historical Item de garantia',
                'verbose_name_plural': 'historical Itens de garantia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Descrição detalhada do item de garantia', max_length=500, verbose_name='Descrição do item')),
                ('item_type', models.CharField(choices=[('documento', 'Documento'), ('eletronico', 'Eletrónico'), ('veiculo', 'Veículo'), ('imovel', 'Imóvel'), ('joias', 'Joias/Ourivesaria'), ('maquinaria', 'Maquinaria/Equipamento'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Tipo de item')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor estimado (MT)')),
                ('condition', models.CharField(choices=[('novo', 'Novo'), ('bom', 'Bom estado'), ('usado', 'Usado'), ('danificado', 'Danificado'), ('não_aplicavel', 'Não aplicável')], default='não_aplicavel', max_length=30, verbose_name='Estado/Conservação')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de série / Identificação')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collateral', to='loans.loan', verbose_name='Empréstimo')),
            ],
            options={
                'verbose_name': 'Item de garantia',
                'verbose_name_plural': 'Itens de garantia',
                'indexes': [models.Index(fields=['loan'], name='loans_colla_loan_id_213263_idx')],
            },
        ),
    ]
