# Generated by Django 5.2.12 on 2026-03-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_add_collateral'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='method_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especificar método (quando Outro)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method_other',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especificar método (quando Outro)'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='method',
            field=models.CharField(choices=[('transferencia', 'Transferência'), ('m_pesa', 'M-Pesa'), ('emola_mkesh', 'eMola Mkesh'), ('deposito', 'Depósito'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('transferencia', 'Transferência'), ('m_pesa', 'M-Pesa'), ('emola_mkesh', 'eMola Mkesh'), ('deposito', 'Depósito'), ('dinheiro', 'Dinheiro'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='Método'),
        ),
    ]
