# Generated by Django 5.2.12 on 2026-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_add_payment_method_emola_and_method_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='receipt_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Ficheiro do recibo'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/%Y/%m/', verbose_name='Ficheiro do recibo'),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='receipt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referência do recibo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referência do recibo'),
        ),
    ]
