# Generated by Django 5.2.12 on 2026-03-12 09:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_add_receipt_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLoanCategory',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('frequency_days', models.PositiveIntegerField(default=30, help_text='Ex.: 30 = mensal, 15 = quinzenal, 365 = anual.', verbose_name='Frequência de pagamento (dias)')),
                ('min_term_days', models.PositiveIntegerField(default=30, verbose_name='Prazo mínimo (dias)')),
                ('max_term_days', models.PositiveIntegerField(default=365, verbose_name='Prazo máximo (dias)')),
                ('min_installments', models.PositiveIntegerField(default=1, verbose_name='Número mínimo de parcelas')),
                ('max_installments', models.PositiveIntegerField(default=12, verbose_name='Número máximo de parcelas')),
                ('collateral_grace_days', models.PositiveIntegerField(default=60, help_text='Após este período de atraso sem cumprir condições, a garantia pode ser executada.', verbose_name='Tolerância para perda da garantia (dias)')),
                ('require_interest_paid_to_keep_collateral', models.BooleanField(default=True, help_text='Se activo, pagar juros a cada período evita perder o bem, mesmo com principal em aberto.', verbose_name='Manter garantia se juros pagos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Categoria de Empréstimo',
                'verbose_name_plural': 'historical Categorias de Empréstimo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LoanCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('frequency_days', models.PositiveIntegerField(default=30, help_text='Ex.: 30 = mensal, 15 = quinzenal, 365 = anual.', verbose_name='Frequência de pagamento (dias)')),
                ('min_term_days', models.PositiveIntegerField(default=30, verbose_name='Prazo mínimo (dias)')),
                ('max_term_days', models.PositiveIntegerField(default=365, verbose_name='Prazo máximo (dias)')),
                ('min_installments', models.PositiveIntegerField(default=1, verbose_name='Número mínimo de parcelas')),
                ('max_installments', models.PositiveIntegerField(default=12, verbose_name='Número máximo de parcelas')),
                ('collateral_grace_days', models.PositiveIntegerField(default=60, help_text='Após este período de atraso sem cumprir condições, a garantia pode ser executada.', verbose_name='Tolerância para perda da garantia (dias)')),
                ('require_interest_paid_to_keep_collateral', models.BooleanField(default=True, help_text='Se activo, pagar juros a cada período evita perder o bem, mesmo com principal em aberto.', verbose_name='Manter garantia se juros pagos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Categoria de Empréstimo',
                'verbose_name_plural': 'Categorias de Empréstimo',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='loans_loanc_code_1f5b9e_idx'), models.Index(fields=['is_active'], name='loans_loanc_is_acti_00263c_idx')],
            },
        ),
        migrations.AddField(
            model_name='historicalloan',
            name='category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='loans.loancategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='loan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.loancategory', verbose_name='Categoria'),
        ),
    ]
