# Generated by Django 5.2.12 on 2026-03-13 13:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_loancategory_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloancategory',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxa sugerida ao criar um novo empréstimo desta categoria (não altera empréstimos já existentes).', max_digits=5, verbose_name='Taxa de juro padrão (%)'),
        ),
        migrations.AddField(
            model_name='historicalloancategory',
            name='default_term_months',
            field=models.PositiveIntegerField(default=12, help_text='Número de meses sugerido ao criar um novo empréstimo desta categoria.', verbose_name='Prazo padrão (meses)'),
        ),
    ]
