# Generated by Django 5.2.12 on 2026-03-14 12:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_historicalloancategory_default_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloancategory',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Empréstimos com montante <= este valor (ou sem limite se vazio).', max_digits=14, null=True, verbose_name='Montante máximo (MT)'),
        ),
        migrations.AddField(
            model_name='historicalloancategory',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Empréstimos com montante >= este valor podem usar esta categoria.', max_digits=14, verbose_name='Montante mínimo (MT)'),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Empréstimos com montante <= este valor (ou sem limite se vazio).', max_digits=14, null=True, verbose_name='Montante máximo (MT)'),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Empréstimos com montante >= este valor podem usar esta categoria.', max_digits=14, verbose_name='Montante mínimo (MT)'),
        ),
    ]
