# Generated by Django 5.2.12 on 2026-03-14 12:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_add_category_amount_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloancategory',
            name='late_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentagem mensal sobre saldo em atraso. Ex.: 2 = 2% ao mês.', max_digits=5, verbose_name='Taxa de juros de mora (%)'),
        ),
        migrations.AddField(
            model_name='historicalloancategory',
            name='max_late_interest_months',
            field=models.PositiveIntegerField(default=12, help_text='Após este número de meses, os juros param de acumular.', verbose_name='Máx. meses de juros de mora'),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='late_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentagem mensal sobre saldo em atraso. Ex.: 2 = 2% ao mês.', max_digits=5, verbose_name='Taxa de juros de mora (%)'),
        ),
        migrations.AddField(
            model_name='loancategory',
            name='max_late_interest_months',
            field=models.PositiveIntegerField(default=12, help_text='Após este número de meses, os juros param de acumular.', verbose_name='Máx. meses de juros de mora'),
        ),
    ]
