# Generated by Django 5.2.12 on 2026-05-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loan_sector'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loancontractproof',
            new_name='loans_loanc_loan_id_00d1c7_idx',
            old_name='loans_loanc_loan_id_7a2b0c_idx',
        ),
        migrations.RenameIndex(
            model_name='loancontractproof',
            new_name='loans_loanc_contrac_00e678_idx',
            old_name='loans_loanc_contract_3a2d1a_idx',
        ),
    ]
